---
title: "Lab_grade_analysis"
author: "Eloise Vannier"
format: html
---
```{r}
#| echo: false
#| message: false
here::i_am("r-101-grade-analysis.Rproj")
library(here)
library(vroom)
library(dplyr)
library(tidyr)
library(ggplot2)
```

## Question 1 :

```{r}
#| echo: false
#| message: false
grades <- vroom(here("grades.csv"),delim = ",")
```

## Question 2 :

```{r}
#| echo: false
#| message: false
grades |> summarise(Min = min(Exam,na.rm=TRUE),Max =max(Exam,na.rm=TRUE),Median =median(Exam,na.rm=TRUE),Mean =mean(Exam,na.rm=TRUE))|>
knitr::kable()
```
## Question 3 :
```{r}
#| echo: false
#| message: false
absents <- grades |> count(is.na(Exam))
```

`r absents$TRUE` students did not attend to the final exam.

## Question 4 :
```{r}
exam <- grades|>
  filter(Exam != is.na(Exam))
ggplot(exam, aes(x=Exam))+geom_histogram(bins = 40)+geom_rug(alpha=0.02)
```
## Question 5 :
```{r}
nb_per_grp <- grades |> group_by(Group)|> summarize(N=n()) 
knitr::kable(nb_per_grp)
```

## Question 6 :
```{r}
grades |> group_by(Group)|>
  ggplot(aes(x=Group))+geom_bar()
```




